### ISSUE TITLE
Add benchmarks

### ISSUE THREAD

**Issue by kodaj** [dusk-network/zelbet#47]
**Describe what you want implemented** 
Benchmark Zelbet against the [reference implementation](https://extgit.iaik.tugraz.at/krypto/zkfriendlyhashzoo/-/tree/master/plain_impls/src).

**Describe "Why" this is needed**
There are no benchmarks yet at the time of writing.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by moCello** [comment]
Can you specify a bit more what is meant with benchmarks? Do you mean a text of some sort comparing our implementation with another implementation? Because at the time of writing there are benchmarks for the following functions in both their `hash` and `gadget` version:
- bars::compose
- bars::decompose
- bars
- permutation
- sponge

**Comment by kodaj** [comment]
I believe Emanuele meant comparing the performance of our implementation to that of the reference implementation. Let's discuss this in more detail when I'm over Covid (hopefully by Monday).

**Comment by moCello** [comment]
closing this issue because there are benchmarks for this crate already. Feel free to reopen once it is clear what exactly we want to bench additionally.
